### ISSUE TITLE
undefined script:

### ISSUE THREAD

**Issue by ahsanlt** [signnow/SignNowPHPSDK#1]
Hey,

I'm running run.php file. It returning me 

Undefined script: 

Error. The parameters array in config.php file script is not defined.

**Comment by onofriichuk-kyrylo** [comment]
Hey @ahsanlt 
You should run this script with required parameters. In your case i think you trying to run script that are not configured in examples/config/config.php.
Please can you provide full command that you trying to run?

**Comment by onofriichuk-kyrylo** [comment]
Hey @ahsanlt
Sorry, you had to stumble upon this script. 
There might be a problem with the required parameters for it. Probably, some of them have not been configured in examples/config/config.php. 
Could you please send me the full command that you're trying to run? I'll check what parameters could be missing and get back to you on this.
