### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by ericksho** [signnow/SignNowPHPSDK#17]
[Documentation](https://github.com/signnow/SignNowPHPSDK#create-a-simple-free-form-invite-to-sign-a-document) mentions method `setSubject` as part of `Invite` class, but its from `Recipient` class

**Comment by JiSoft** [comment]
Fixed at 
[v2.2.3](https://github.com/signnow/SignNowPHPSDK/releases/tag/v2.2.3)
[v1.5.3](https://github.com/signnow/SignNowPHPSDK/releases/tag/v1.5.3)
