### ISSUE TITLE
Move document to a specific folder

### ISSUE THREAD

**Issue by idirocco** [signnow/SignNowPHPSDK#18]
Hi there, please correct me if I'm wrong but it looks like the "move document" feature is not implemented yet as it's stated here https://docs.signnow.com/docs/signnow/b54be27733fd7-move-document

Do you have any plan to implement it? Can I contribute to it?

Thanks!

**Comment by JiSoft** [comment]
Implemented:

- [v1.5.5](https://github.com/signnow/SignNowPHPSDK/releases/tag/v1.5.5)
- [v2.5.5](https://github.com/signnow/SignNowPHPSDK/releases/tag/v2.2.5)
