### ISSUE TITLE
$updateHttpMethod = Request::METHOD_PATCH

### ISSUE THREAD

**Issue by keithslater** [signnow/SignNowPHPSDK#2]
I believe the updateHttpMethod should be a PUT

**Comment by falgonua** [comment]
Hello  @keithslater.
Yes, you are right. In case of https://github.com/signnow/SignNowPHPSDK updateHttpMethod should be PUT. You could set it via `EntityManager::setUpdateHttpMethod(string $updateHttpMethod)`. Its described in readme https://github.com/signnow/SignNowPHPSDK#setting-up.
https://github.com/signnow/RestEntityManager is developed without any dependencies of our API. And we decided use PATCH method as default between PUT/PATCH for `EntityManager::update(Entity $entity, $uriParams = [], $queryParams = [], array $headers = [])`.
