### ISSUE TITLE
Add smart fields support

### ISSUE THREAD

**Issue by Marcel-Sass** [signnow/SignNowPHPSDK#21]
i need support for refilling smart fields: https://docs.signnow.com/docs/signnow/acbd8896f7aac-prefill-smart-fields
Is there a Plan for implementing this? or is there a easy workaround to create this request with the entity manager?

**Comment by Vasyl-Kravets** [comment]
Added at
[v2.2.4](https://github.com/signnow/SignNowPHPSDK/releases/tag/v2.2.4)
[v1.5.4](https://github.com/signnow/SignNowPHPSDK/releases/tag/v1.5.4)
